# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def pods
 pod 'Alamofire', '~> 5.4'
 pod 'SwiftyJSON', '~> 4.0'
end

target 'RestfulAPI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pods
  # Pods for RestfulAPI

  target 'RestfulAPITests' do
    inherit! :search_paths
    # Pods for testing
    pods
  end

  target 'RestfulAPIUITests' do
    # Pods for testing
  end

end
