# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

def pods
 pod 'RxSwift'
 pod 'RxCocoa'
 pod 'ReactorKit'
 pod 'Alamofire'
 pod 'Kingfisher'
end

target 'BookFriend' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pods
  # Pods for BookFriend

  target 'BookFriendTests' do
    inherit! :search_paths
    # Pods for testing
    pods
  end

  target 'BookFriendUITests' do
    # Pods for testing
    pods
  end

end
